### PR TITLE
Add assert handling

### PR DESCRIPTION
**Pull request by evantypanski**
in Zeek grammar:

https://github.com/zeek/zeek/blob/e4dbba20a4c7ff827ba481cec97e33d96b31f1df/src/parse.y#L1850-L1853

https://github.com/zeek/zeek/blob/e4dbba20a4c7ff827ba481cec97e33d96b31f1df/src/parse.y#L2281-L2286

### CODE REVIEW

**Comment by evantypanski** [comment]
I think my generated parser is a little different since I'm on 0.24.3 - not sure if that matters. I can push the updated generated files if that's preferable, though :)

**Review by bbannier — APPROVED** [review]
Looks good to me. The alternative would be to use [named fields](https://tree-sitter.github.io/tree-sitter/creating-parsers#using-fields) instead of producing a more elaborate CST with `assert_msg` nodes, but in general this grammar stays extremely close to Zeek's own Bison grammar so the current approach fits in well. Also thanks for adding a test!

As for the generated parser, let's add a file matching the dependencies. An easy way to do that would be to use npm,

```console
$ npm i
$ npm exec tree-sitter generate --no-bindings
```

**Comment by bbannier** [comment]
While at it you could also add `assert` as a keyword to `queries/highlights.scm`.

**Comment by evantypanski** [comment]
CI is still mad with the generated files, though :(

**Comment by evantypanski** [comment]
for the record I had to do this to get the correct tree sitter CLI version for CI:

```
$ npm install tree-sitter-cli@0.23.2
$ npm exec tree-sitter generate --no-bindings
```

my `tree-sitter` in `PATH` is still `0.24.3`

I think since the package uses `^0.23.0` it's ok with `0.24`, but that makes CI fail:

https://github.com/zeek/tree-sitter-zeek/blob/3c8742c0b1ba55d34241fd42056eb59733426f54/package.json#L39

maybe worth locking that in at some point?

**Comment by bbannier** [comment]
> I think since the package uses `^0.23.0` it's ok with `0.24`, but that makes CI fail:
> 
> https://github.com/zeek/tree-sitter-zeek/blob/3c8742c0b1ba55d34241fd42056eb59733426f54/package.json#L39
> 
> maybe worth locking that in at some point?

Yes, we should definitely pin this and while at it might even bump to `tree-sitter-0.24.3`.

**Pull request merged**
